language: ruby
rvm:
  - 2.6
env:
  global:
    - TESLA_EMAIL=elon.musk@teslamotors.com
    - TESLA_PASS=oilLOL
    - TESLA_CLIENT_ID=1
    - TESLA_CLIENT_SECRET=2
    - TESLA_API_TOKEN=3
notifications:
  email: false
